name: geomstats-condamklnumpy

channels:
  # not installing autograd, thus conda-forge not needed
  #- conda-forge
  # defaults channel for installing mkl numpy
  - defaults

dependencies:
  - python=3.7.*
  #- autograd=1.3
  - jupyter
  - joblib=0.14.1
  - matplotlib
  - numpy>=1.18.1
  - pandas
  - scikit-learn>=0.22.1
  - scipy>=1.4.1
