name: geomstats-condamkl2numpy

channels:
  # pick numpy from defaults (mkl numpy) and missing packages (autograd) from conda-forge
  - defaults
  - conda-forge

dependencies:
  - python=3.7.*
  - autograd=1.3
  - jupyter
  - joblib=0.14.1
  - matplotlib
  - numpy>=1.18.1
  - pandas
  - scikit-learn>=0.22.1
  - scipy>=1.4.1
